language: d

script:
  - dub upgrade
#  Coverage disabled because we are hitting this bug:
#  https://github.com/rejectedsoftware/vibe.d/issues/767
#  - dub test --coverage --compiler=${DC}
  - dub test --compiler=${DC}

after_success:
  - bash <(curl -s https://codecov.io/bash)
